#! python
# Generate output names list

out_names = []
for i in [1, 2, 4, 5, 6, 7]:
    names = ["", "", ""]
    names[0] = "sharew" + str(i) + "_rel7-0-0_ep.dta"
    names[1] = "sharew" + str(i) + "_rel7-0-0_co.dta"
    names[2] = "sharew" + str(i) + "_rel7-0-0_cv_r.dta"
    out_names.append(names)


def build(ctx):

    # Illustrate simple use of run_py_script
    for list in out_names:
        for name in list:
            ctx(
                features="run_py_script",
                source="merging_data.py",
                deps=[ctx.path_to(ctx, "IN_DATA", name)],
                target=ctx.path_to(ctx, "OUT_DATA", "share_merged.pkl"),
                name="merged_data",
            )

    ctx(
        features="run_py_script",
        source="merging_data.py",
        deps=[ctx.path_to(ctx, "IN_DATA", "sharew1_rel7-0-0_gv_isced.dta")],
        target=ctx.path_to(ctx, "OUT_DATA", "share_merged.pkl"),
        name="merged_data",
    )

    ctx(
        features="run_py_script",
        source="cleaning_data.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "share_merged.pkl")],
        target=ctx.path_to(ctx, "OUT_DATA", "share_final.csv"),
        name="share_final",
    )
