name: consumption_behaviuor_during_retirment
channels:
  - defaults

dependencies:
  - ipykernel=5.1.3
  - matplotlib
  - jupyterlab=1.1.4
  - pandas=0.25.1
  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8
  - nb_conda_kernels=2.2.2
  - statsmodels

  - pip:
    - click==7.0
    - functools
    - linearmodels
    - pre-commit==1.18.3

    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3

    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0
