#! python
# Generate output names list
years_classes = [[1923, 1939], [1940, 1955], [1956, 1978]]

out_names = []
for format in [".tex", ".pkl"]:
    for y in years_classes:
        if format == ".pkl":
            for var in ["_par", "_std"]:
                names = ["", ""]
                names[0] = (
                    "sub_" + "exret_" + str(y[0]) + "_" + str(y[1]) + var + format
                )
                names[1] = (
                    "sub_" + "job_Retired_" + str(y[0]) + "_" + str(y[1]) + var + format
                )
                out_names.append(names)
        else:
            names = ["", ""]
            names[0] = "sub_" + "exret_" + str(y[0]) + "_" + str(y[1]) + format
            names[1] = "sub_" + "job_Retired_" + str(y[0]) + "_" + str(y[1]) + format
            out_names.append(names)


def build(ctx):

    # Illustrate simple use of run_py_script
    for list in out_names[:3]:
        for name in list:
            ctx(
                features="run_py_script",
                source="regression.py",
                deps=[ctx.path_to(ctx, "OUT_DATA", "share_final.csv")],
                target=ctx.path_to(ctx, "OUT_TABLES", name),
                name="sub_regression",
            )

    for list in out_names[3:]:
        for name in list:
            ctx(
                features="run_py_script",
                source="regression.py",
                deps=[ctx.path_to(ctx, "OUT_DATA", "share_final.csv")],
                target=ctx.path_to(ctx, "OUT_DATA", name),
                name="sub_regression",
            )

    ctx(
        features="run_py_script",
        source="regression.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "share_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_TABLES", "main_regression_exret.tex"),
            ctx.path_to(ctx, "OUT_TABLES", "main_regression_job_Retired.tex"),
        ],
        name="main_regression",
    )

    for list in out_names[3:]:
        for name in list:
            ctx(
                features="run_py_script",
                source="visualizing_data.py",
                deps=[ctx.path_to(ctx, "OUT_DATA", name)],
                target=[
                    ctx.path_to(ctx, "OUT_FIGURES", "CI_exret.pdf"),
                    ctx.path_to(ctx, "OUT_FIGURES", "CI_job_Retired.pdf"),
                ],
                name="visualization",
            )
