#! python
# Generate output names list

out_names = []
for i in [1923, 1940, 1956]:
    for y in [1939, 1955, 1978]:
        names = ["", ""]
        names[0] = "sub_regression_" + "exret_" + str(i) + "_" + str(y) + ".tex"
        names[1] = "sub_regression_" + "job_Retired_" + str(i) + "_" + str(y) + ".tex"


def build(ctx):

    # Illustrate simple use of run_py_script
    for list in out_names:
        for name in list:
            ctx(
                features="run_py_script",
                source="regression.py",
                deps=[ctx.path_to(ctx, "OUT_DATA", "share_final.csv")],
                target=ctx.path_to(ctx, "OUT_TABLES", name),
                name="regression",
            )
    ctx(
        features="run_py_script",
        source="regression.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "share_final.csv")],
        target=[
            ctx.path_to(ctx, "OUT_TABLES", "main_regression_exret.tex"),
            ctx.path_to(ctx, "OUT_TABLES", "main_regression_job_Retired.tex"),
        ],
        name="regression",
    )
